<?php

namespace Buseta\TallerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImpuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpuestoRepository extends EntityRepository
{
}
