<?php

namespace Buseta\BodegaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{
    public function informeStock($busqueda,$em)
    {
        $entities = $em->createQueryBuilder()
            ->select('p')
            ->from('BusetaBodegaBundle:Producto','p');

        $datos = $busqueda->getData();

        $entities
            ->where('p.id = :producto');
        $entities
            ->setParameter('producto', $datos->getProducto());

        if($datos->getCategoria()){
            $entities->andWhere('p.categoria.id = :categoria');
            $entities->setParameter('categoria', $datos->getCategoria());
        }

        $entities = $entities
            ->getQuery();

        return $entities;
    }

    public function buscarTodos($em)
    {
        $entities = $em->createQueryBuilder()
            ->select('p')
            ->from('BusetaBodegaBundle:Producto','p');

        $entities = $entities
            ->getQuery();

        return $entities;
    }

}
