<?php

namespace Buseta\BodegaBundle\Entity;

use Buseta\NomencladorBundle\Entity\Categoria;
use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{
    public function informeStock($busqueda,$em)
    {
        $entities = $em->createQueryBuilder()
            ->select('p')
            ->from('BusetaBodegaBundle:Producto','p');

        $datos = $busqueda->getData();

        if($datos->getProducto()){
            $entities
                ->where('p.id = :producto');
            $entities
                ->setParameter('producto', $datos->getProducto());
        }


        if($datos->getCategoria()){
            $entities->andWhere('c.id = :categoria');
            $entities->leftJoin('p.categoria', 'c');
            $entities->setParameter('categoria', $datos->getCategoria()->getId());
        }

        $entities = $entities
            ->getQuery();

        return $entities;
    }

    public function buscarTodos($em)
    {
        $entities = $em->createQueryBuilder()
            ->select('p')
            ->from('BusetaBodegaBundle:Producto','p');

        $entities = $entities
            ->getQuery();

        return $entities;
    }

}
